### PR TITLE
QoL improvements to code

### PR DESCRIPTION
**Pull request by tfuxu**
I found out about this project last week, and thought it would be nice to contribute something to it, to make it at least a little bit more user-friendly for others. Here's a list of changes I've made:

- Fixed error in line 51 where undefined class was used,
- Added two new checks in Auth class for "Authentication Required" response and for unknown errors,
- Created requirements.txt and .gitignore,
- Added color indicators to XiaomiError and UserError outputs ([ERROR] text in red color),
- Moved shebang (#!) from request.py to main.py,
- Slightly modified README.md

Also, adb library from now will use `rsa` instead of `pycryptodome`.

### CODE REVIEW

**Comment by Luciogi** [comment]
Does these changes working for you?
For me they are not, after pasting response
```
Traceback (most recent call last):
  File "/home/oggy/miunlock/./main.py", line 23, in <module>
    auth.login_tui("unlockApi")
  File "/home/oggy/miunlock/request.py", line 23, in login_tui
    self.login(input("Go to account.xiaomi.com,log in and paste the code inside code.txt\n(dont forget to change the username and password or else it will fail)\nto devtools console (press f12 then select console) then copypaste the response to here: ".format(self.LOGIN_URL.format(sid)))) # please edit this,this is so bad
  File "/home/oggy/miunlock/request.py", line 55, in login
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://unlock.update.miui.com/(personal_info)
```

**Comment by tfuxu** [comment]
> I used this pull request, but still not working, after pasting response
> 
> ```
> Traceback (most recent call last):
>   File "/home/user1/miunlock/./main.py", line 23, in <module>
>     auth.login_tui("unlockApi")
>   File "/home/user1/miunlock/request.py", line 23, in login_tui
>     self.login(input("Go to account.xiaomi.com,log in and paste the code inside code.txt\n(dont forget to change the username and password or else it will fail)\nto devtools console (press f12 then select console) then copypaste the response to here: ".format(self.LOGIN_URL.format(sid)))) # please edit this,this is so bad
>   File "/home/user1/miunlock/request.py", line 55, in login
>     response.raise_for_status()
>   File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://unlock.update.miui.com/(personal_info)
> ```

@Luciogi Hmm that's interesting. Could you, please send me what response have you got?

**Comment by tfuxu** [comment]
Oh, I think that I know what's happening. You've probably copied response from Firefox DevTools or some other browser DevTool in which links are shortened in console output. The problem with that is (at least in Firefox) when something is outputting huge links, console will remove the center of URL and replace it with … unicode symbol. If you want to get full URL, you need to do this (at least in Firefox):

1. Right-click link,
2. Choose 'Copy Link Location' from dropdown menu, 
3. Replace shortened link with this proper one in response.

**Comment by Luciogi** [comment]
Yes Now it is proceeding without errors

**Comment by Canny1913** [comment]
people care about this fork wow
thanks

**Pull request merged**
